[workspace]
members = ["smolnn2-macro"]
[package]
name = "smolnn2"
version = "0.1.0"
edition = "2024"

[dependencies]
smolmatrix = "0.1.8"
smolnn2-macro = { version = "0.1.0", path = "smolnn2-macro", optional = true }

[dev-dependencies]
fastrand = "2.3.0"

[features]
macro = ["dep:smolnn2-macro"]
