[package]
name = "mnist"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
smolmatrix = { version = "0.1.9", features = ["serde"] }
smolnn2 = { version = "0.1.0", path = "..", features = ["macro"] }
